# Generated by Django 2.1.1 on 2018-09-26 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rendhtml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('nick', models.CharField(max_length=10, unique=True, verbose_name='昵称')),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='父分类')),
            ],
        ),
    ]
