# Generated by Django 2.1.1 on 2018-09-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendhtml', '0002_userext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='名称')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='图片')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='简介')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='菜单显示')),
                ('show_in_home', models.BooleanField(default=True, verbose_name='首页显现')),
                ('create_data', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rendhtml.Category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
    ]
