# Generated by Django 2.1.1 on 2018-09-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendhtml', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标题')),
                ('keyword', models.CharField(blank=True, max_length=300, null=True, verbose_name='关键字')),
                ('brief', models.CharField(blank=True, max_length=100, null=True, verbose_name='简短描述')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场售价')),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='本店售价')),
                ('thumb', models.ImageField(upload_to='goods/', verbose_name='缩略图')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendhtml.Category', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
