# Generated by Django 2.1.1 on 2018-10-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendhtml', '0007_auto_20181011_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], default='未支付', verbose_name='是否支付'),
        ),
    ]
