# Generated by Django 2.1.1 on 2018-10-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendhtml', '0008_auto_20181011_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='是否支付'),
        ),
    ]
